name: cielo_zero_auth
description: A Flutter package that helps to use Cielo's Zero Auth.
version: 1.0.0
homepage: https://github.com/developercielo/cielo-zero-auth-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  cielo_oauth: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: